<?php

declare(strict_types=1);

/**
 * phpMyAdmin config for DB Vault signon.
 *
 * auth_type 'signon' means phpMyAdmin never shows a login form: it reads the
 * MySQL credential from the SignonSession that signon.php populated after
 * exchanging the vault's one-time token. Users can only ever arrive here via
 * a valid DB Vault launch.
 */

$cfg['blowfish_secret'] = 'dbvault-local-demo-blowfish-secret-32byte!!';

// Served natively under a sub-path ("{vault-path}/pma") on the host's own
// origin/TLS, phpMyAdmin needs its self-URL pinned to that base so redirects
// and asset links resolve. PmaAbsoluteUri does that. The web-server config
// generated by `dbvault:pma-vhost` passes DBVAULT_PMA_ABSOLUTE_URI in as a
// fastcgi_param/SetEnv, e.g. "https://example.test/vault/pma/". Falls back to
// phpMyAdmin's own auto-detection if unset.
$pmaAbsoluteUri = $_SERVER['DBVAULT_PMA_ABSOLUTE_URI'] ?? (getenv('DBVAULT_PMA_ABSOLUTE_URI') ?: '');
if (is_string($pmaAbsoluteUri) && $pmaAbsoluteUri !== '') {
    $cfg['PmaAbsoluteUri'] = rtrim($pmaAbsoluteUri, '/').'/';
}

$i = 1;
$cfg['Servers'][$i]['auth_type'] = 'signon';
$cfg['Servers'][$i]['SignonSession'] = 'SignonSession';
$cfg['Servers'][$i]['SignonURL'] = 'signon.php';
// Host is supplied per-session by signon.php (PMA_single_signon_host), but a
// default keeps pMA happy at bootstrap.
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

// Local demo niceties.
$cfg['TempDir'] = sys_get_temp_dir().'/pma-tmp';
@mkdir($cfg['TempDir'], 0700, true);
