#!/usr/bin/env bash
#
# DB Vault — phpMyAdmin (signon) installer   [REQUIRED]
# ----------------------------------------------------------------------------
# Downloads phpMyAdmin and configures it in "signon" auth mode so that clicking
# "phpMyAdmin" in the DB Vault panel logs the user straight in as their
# temporary, scoped MySQL account — no login form, password never shown.
#
# It installs two DB-Vault-specific files:
#   - config.inc.php   -> auth_type 'signon'
#   - signon.php       -> exchanges the vault's one-time token for the temp
#                         credential via the vault's /sessions/exchange API
#
# Usage:
#   chmod +x install-phpmyadmin.sh
#   sudo ./install-phpmyadmin.sh
#
# Configure via env vars (all have sensible defaults):
#   PMA_VERSION        phpMyAdmin release        (default 5.2.2)
#   PMA_DIR            install target dir         (default /var/www/phpmyadmin)
#   PMA_PORT           port for the built-in dev server (default 8080; 0 = skip serving)
#   VAULT_EXCHANGE_URL vault token-exchange endpoint
#                        (default http://127.0.0.1:8000/vault/api/sessions/exchange)
#   VAULT_SIGNON_SECRET shared secret; MUST equal DBVAULT_SIGNON_SECRET in the
#                        vault host app's .env  (default: generated & printed)
# ----------------------------------------------------------------------------
set -euo pipefail

PMA_VERSION="${PMA_VERSION:-5.2.2}"
PMA_DIR="${PMA_DIR:-/var/www/phpmyadmin}"
PMA_PORT="${PMA_PORT:-8080}"
VAULT_EXCHANGE_URL="${VAULT_EXCHANGE_URL:-http://127.0.0.1:8000/vault/api/sessions/exchange}"
VAULT_SIGNON_SECRET="${VAULT_SIGNON_SECRET:-$(head -c 24 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)}"

say() { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

command -v php  >/dev/null || die "php is required."
command -v curl >/dev/null || die "curl is required."
command -v unzip >/dev/null || die "unzip is required."

say "Downloading phpMyAdmin ${PMA_VERSION}..."
tmp="$(mktemp -d)"
curl -fsSL -o "$tmp/pma.zip" \
  "https://files.phpmyadmin.net/phpMyAdmin/${PMA_VERSION}/phpMyAdmin-${PMA_VERSION}-english.zip" \
  || die "download failed"
unzip -q "$tmp/pma.zip" -d "$tmp"

say "Installing into ${PMA_DIR}..."
mkdir -p "$PMA_DIR"
cp -r "$tmp/phpMyAdmin-${PMA_VERSION}-english/." "$PMA_DIR/"
rm -rf "$tmp"

blowfish="$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)"

say "Writing config.inc.php (auth_type = signon)..."
cat > "$PMA_DIR/config.inc.php" <<PHP
<?php
declare(strict_types=1);
// DB Vault signon configuration — generated by install-phpmyadmin.sh
\$cfg['blowfish_secret'] = '${blowfish}';
\$i = 1;
\$cfg['Servers'][\$i]['auth_type']     = 'signon';
\$cfg['Servers'][\$i]['SignonSession']  = 'SignonSession';
\$cfg['Servers'][\$i]['SignonURL']      = 'signon.php';
\$cfg['Servers'][\$i]['host']           = '127.0.0.1';
\$cfg['Servers'][\$i]['port']           = '3306';
\$cfg['Servers'][\$i]['AllowNoPassword'] = false;
\$cfg['TempDir'] = sys_get_temp_dir().'/pma-tmp';
@mkdir(\$cfg['TempDir'], 0700, true);
PHP

say "Writing signon.php (token exchange bridge)..."
cat > "$PMA_DIR/signon.php" <<PHP
<?php
declare(strict_types=1);
// DB Vault -> phpMyAdmin signon bridge — generated by install-phpmyadmin.sh
const VAULT_EXCHANGE_URL  = '${VAULT_EXCHANGE_URL}';
const VAULT_SIGNON_SECRET = '${VAULT_SIGNON_SECRET}';

session_name('SignonSession');
session_start();

\$token = \$_GET['token'] ?? '';
if (\$token === '') { http_response_code(400); exit('Missing signon token. Launch from the DB Vault panel.'); }

\$ch = curl_init(VAULT_EXCHANGE_URL);
curl_setopt_array(\$ch, [
    CURLOPT_POST => true, CURLOPT_RETURNTRANSFER => true, CURLOPT_TIMEOUT => 10,
    CURLOPT_HTTPHEADER => ['Content-Type: application/json','Accept: application/json','X-DbVault-Signon: '.VAULT_SIGNON_SECRET],
    CURLOPT_POSTFIELDS => json_encode(['token' => \$token]),
]);
\$body = curl_exec(\$ch); \$status = curl_getinfo(\$ch, CURLINFO_HTTP_CODE); curl_close(\$ch);
if (\$status !== 200) { http_response_code(403); exit('This session is no longer valid. Return to DB Vault and launch again.'); }

\$cred = json_decode((string) \$body, true);
\$_SESSION['PMA_single_signon_user']      = \$cred['username'];
\$_SESSION['PMA_single_signon_password']  = \$cred['password'];
\$_SESSION['PMA_single_signon_host']      = \$cred['host'];
\$_SESSION['PMA_single_signon_port']      = (string) \$cred['port'];
\$_SESSION['PMA_single_signon_cfgupdate'] = ['only_db' => \$cred['database']];
session_write_close();
header('Location: ./index.php');
exit;
PHP

say "Done. phpMyAdmin installed at ${PMA_DIR}"
echo
echo "  Signon secret (put this in the vault host .env as DBVAULT_SIGNON_SECRET):"
echo "      DBVAULT_SIGNON_SECRET=${VAULT_SIGNON_SECRET}"
echo "  And point the vault at this phpMyAdmin:"
echo "      DBVAULT_PMA_SIGNON_URL=http://<pma-host>:${PMA_PORT}/signon.php"
echo

if [ "$PMA_PORT" != "0" ]; then
  say "Serving phpMyAdmin on http://127.0.0.1:${PMA_PORT} (Ctrl+C to stop)"
  say "In production, serve ${PMA_DIR} with nginx/apache + PHP-FPM instead."
  exec php -S "127.0.0.1:${PMA_PORT}" -t "$PMA_DIR"
fi
