#!/usr/bin/env bash
#
# DB Vault — nginx mTLS reverse proxy   [OPTIONAL]
# ----------------------------------------------------------------------------
# Sets up nginx to terminate HTTPS + verify client certificates against the
# vault's CA, then forward the verification result to the vault app. Only
# needed if you want mutual-TLS device authentication. The vault works fine
# without this (session auth over plain HTTPS).
#
# Prereqs:
#   - nginx installed
#   - a CA cert generated by:  php artisan dbvault:make-ca
#   - the vault app reachable (default http://127.0.0.1:8000)
#
# Usage:
#   chmod +x setup-nginx-mtls.sh
#   sudo ./setup-nginx-mtls.sh
#
# Env vars:
#   LISTEN_PORT   HTTPS port for the vault vhost      (default 8443)
#   APP_UPSTREAM  where the vault app runs            (default 127.0.0.1:8000)
#   CA_CERT       client-CA cert (from make-ca)        (REQUIRED)
#   TLS_DIR       where to write nginx's server cert   (default /etc/dbvault-tls)
#   SERVER_NAME   vhost server_name                    (default localhost)
#   VHOST_PATH    nginx conf file to write     (default /etc/nginx/conf.d/dbvault-mtls.conf)
# ----------------------------------------------------------------------------
set -euo pipefail

LISTEN_PORT="${LISTEN_PORT:-8443}"
APP_UPSTREAM="${APP_UPSTREAM:-127.0.0.1:8000}"
CA_CERT="${CA_CERT:-}"
TLS_DIR="${TLS_DIR:-/etc/dbvault-tls}"
SERVER_NAME="${SERVER_NAME:-localhost}"
VHOST_PATH="${VHOST_PATH:-/etc/nginx/conf.d/dbvault-mtls.conf}"

say() { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

command -v nginx   >/dev/null || die "nginx is not installed."
command -v openssl >/dev/null || die "openssl is required."
[ -n "$CA_CERT" ] || die "Set CA_CERT to your vault CA cert (php artisan dbvault:make-ca)."
[ -f "$CA_CERT" ] || die "CA_CERT not found: $CA_CERT"

say "Generating nginx server certificate (self-signed) in ${TLS_DIR}..."
mkdir -p "$TLS_DIR"
if [ ! -f "$TLS_DIR/server.crt" ]; then
  openssl req -x509 -newkey rsa:2048 -keyout "$TLS_DIR/server.key" -out "$TLS_DIR/server.crt" \
    -days 825 -nodes -subj "/CN=${SERVER_NAME}/O=DB Vault" \
    -addext "subjectAltName=DNS:${SERVER_NAME},DNS:localhost,IP:127.0.0.1"
  chmod 600 "$TLS_DIR/server.key"
else
  say "server.crt already exists — keeping it."
fi

say "Writing vhost ${VHOST_PATH}..."
cat > "$VHOST_PATH" <<NGINX
# DB Vault mTLS reverse proxy — generated by setup-nginx-mtls.sh
server {
    listen ${LISTEN_PORT} ssl;
    server_name ${SERVER_NAME};

    ssl_certificate     ${TLS_DIR}/server.crt;
    ssl_certificate_key ${TLS_DIR}/server.key;

    # Client certs must be signed by the vault CA.
    ssl_client_certificate ${CA_CERT};
    ssl_verify_client optional;   # 'optional' -> app returns clean 403, not a TLS abort
    ssl_verify_depth 2;

    location / {
        proxy_pass http://${APP_UPSTREAM};
        proxy_set_header Host               \$host;
        proxy_set_header X-Real-IP          \$remote_addr;
        proxy_set_header X-Forwarded-For    \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  https;
        proxy_set_header X-Forwarded-Host   \$host;
        proxy_set_header X-Forwarded-Port   ${LISTEN_PORT};

        # mTLS handoff -> config('dbvault.mtls_*_header')
        proxy_set_header X-Client-Verify           \$ssl_client_verify;
        proxy_set_header X-Client-Cert-DN          \$ssl_client_s_dn;
        proxy_set_header X-Client-Cert-Fingerprint "SHA256:\$ssl_client_fingerprint";
    }
}
NGINX

say "Validating and reloading nginx..."
nginx -t
nginx -s reload 2>/dev/null || systemctl reload nginx 2>/dev/null || service nginx reload

say "Done. Vault mTLS vhost live on https://${SERVER_NAME}:${LISTEN_PORT}"
echo
echo "  Next, in the vault host app's .env, ENABLE the mTLS gate:"
echo "      DBVAULT_MIDDLEWARE=\"vault.mtls,web\""
echo "      DBVAULT_MTLS_REQUIRE_ENROLLED_DEVICE=true   # optional device binding"
echo
echo "  IMPORTANT: also configure the host app to TRUST this proxy, or asset"
echo "  URLs render as http (blank SPA). In bootstrap/app.php withMiddleware():"
echo "      \$middleware->trustProxies(at: '*', headers: Request::HEADER_X_FORWARDED_FOR"
echo "          | Request::HEADER_X_FORWARDED_HOST | Request::HEADER_X_FORWARDED_PORT"
echo "          | Request::HEADER_X_FORWARDED_PROTO);"
echo
echo "  Then browse https://${SERVER_NAME}:${LISTEN_PORT}/vault with a client cert installed."
