#!/usr/bin/env bash
#
# DB Vault — apache mTLS reverse proxy   [OPTIONAL — nginx alternative]
# ----------------------------------------------------------------------------
# Apache equivalent of setup-nginx-mtls.sh. Terminates HTTPS, verifies client
# certs against the vault CA, forwards the result to the vault app. Use this
# only if you run apache instead of nginx.
#
# Usage:
#   chmod +x setup-apache-mtls.sh
#   sudo ./setup-apache-mtls.sh
#
# Env vars:
#   LISTEN_PORT   HTTPS port                    (default 8443)
#   APP_UPSTREAM  vault app origin              (default http://127.0.0.1:8000)
#   CA_CERT       client-CA cert (make-ca)       (REQUIRED)
#   TLS_DIR       apache server cert dir         (default /etc/dbvault-tls)
#   SERVER_NAME   ServerName                     (default localhost)
#   VHOST_PATH    apache conf to write   (default /etc/apache2/sites-available/dbvault-mtls.conf)
# ----------------------------------------------------------------------------
set -euo pipefail

LISTEN_PORT="${LISTEN_PORT:-8443}"
APP_UPSTREAM="${APP_UPSTREAM:-http://127.0.0.1:8000}"
CA_CERT="${CA_CERT:-}"
TLS_DIR="${TLS_DIR:-/etc/dbvault-tls}"
SERVER_NAME="${SERVER_NAME:-localhost}"
VHOST_PATH="${VHOST_PATH:-/etc/apache2/sites-available/dbvault-mtls.conf}"

say() { printf '\033[1;36m==>\033[0m %s\n' "$1"; }
die() { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

command -v apache2 >/dev/null || command -v httpd >/dev/null || die "apache is not installed."
command -v openssl >/dev/null || die "openssl is required."
[ -n "$CA_CERT" ] || die "Set CA_CERT to your vault CA cert (php artisan dbvault:make-ca)."
[ -f "$CA_CERT" ] || die "CA_CERT not found: $CA_CERT"

say "Enabling required apache modules..."
a2enmod ssl proxy proxy_http headers >/dev/null 2>&1 || say "(enable ssl, proxy, proxy_http, headers manually if a2enmod is unavailable)"

say "Generating apache server certificate in ${TLS_DIR}..."
mkdir -p "$TLS_DIR"
if [ ! -f "$TLS_DIR/server.crt" ]; then
  openssl req -x509 -newkey rsa:2048 -keyout "$TLS_DIR/server.key" -out "$TLS_DIR/server.crt" \
    -days 825 -nodes -subj "/CN=${SERVER_NAME}/O=DB Vault" \
    -addext "subjectAltName=DNS:${SERVER_NAME},DNS:localhost,IP:127.0.0.1"
  chmod 600 "$TLS_DIR/server.key"
fi

say "Writing vhost ${VHOST_PATH}..."
cat > "$VHOST_PATH" <<APACHE
# DB Vault mTLS reverse proxy — generated by setup-apache-mtls.sh
Listen ${LISTEN_PORT}
<VirtualHost *:${LISTEN_PORT}>
    ServerName ${SERVER_NAME}

    SSLEngine on
    SSLCertificateFile      ${TLS_DIR}/server.crt
    SSLCertificateKeyFile   ${TLS_DIR}/server.key

    # Verify client certs against the vault CA. 'optional' lets the app return
    # a clean 403 for unauthenticated requests instead of a TLS-level failure.
    SSLCACertificateFile    ${CA_CERT}
    SSLVerifyClient         optional
    SSLVerifyDepth          2
    SSLOptions              +StdEnvVars +ExportCertData

    ProxyPreserveHost On
    ProxyPass        / ${APP_UPSTREAM}/
    ProxyPassReverse / ${APP_UPSTREAM}/

    RequestHeader set X-Forwarded-Proto "https"
    RequestHeader set X-Forwarded-Port  "${LISTEN_PORT}"
    # mTLS handoff -> config('dbvault.mtls_*_header')
    RequestHeader set X-Client-Verify           "%{SSL_CLIENT_VERIFY}s"
    RequestHeader set X-Client-Cert-DN          "%{SSL_CLIENT_S_DN}s"
    RequestHeader set X-Client-Cert-Fingerprint "SHA256:%{SSL_CLIENT_M_SERIAL}s"
</VirtualHost>
APACHE

say "Enabling site and reloading apache..."
a2ensite dbvault-mtls >/dev/null 2>&1 || true
apachectl configtest
systemctl reload apache2 2>/dev/null || service apache2 reload 2>/dev/null || apachectl -k graceful

say "Done. Vault mTLS vhost live on https://${SERVER_NAME}:${LISTEN_PORT}"
echo
echo "  Then in the vault host app .env enable the gate and trust the proxy"
echo "  (see setup-nginx-mtls.sh notes; identical app-side steps)."
echo
echo "  NOTE: apache exposes the SHA-1 client fingerprint differently across"
echo "  versions; DB Vault device-matching falls back to the certificate CN,"
echo "  so device binding works regardless."
